AWSTemplateFormatVersion: 2010-09-09

Description: Deploy infrastructure through codepipeline 

Resources: 
    MyPipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties: 
          ArtifactStore: 
              Location: holmesdemo
              Type: S3
          RestartExecutionOnUpdate: true
          RoleArn: !GetAtt MyCodePipelineExecutionServiceRole.Arn
          Stages: 
          - Actions: 
            - ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: nerdpractitioner
                Repo: stelligent-university
                PollForSourceChanges: 'true'
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:matthewholmes/github/personal-access-token:SecretString:OAuthToken}}'
              InputArtifacts: []
              OutputArtifacts:
              - Name: MyArtifact
              Name: checkout-code
              Region: us-east-1
            Name: checkout
          - Actions: 
            - ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                StackName: bucket-stack-holmes
                TemplatePath: MyArtifact::bucket.yaml
                RoleArn: !GetAtt MyCloudformationExecutionServiceRole.Arn
              OutputArtifacts: []
              InputArtifacts:
              - Name: MyArtifact 
              Name: Create-S3-Bucket
              Region: us-east-1
            Name: Deploy
          Tags: 
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.1'
          - Key: stelligent-u-lab
            Value: '12.1.1'

#codepipeline execution role to execute cloudformation and access S3
    MyCodePipelineExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codepipeline.amazonaws.com
          Policies:
          - PolicyName: cfn-execution-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                  - 's3:*'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'iam:PassRole'
                  Resource: "*"

# execution role that trust cloudformation to create an S3 bucket   
    MyCloudformationExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: cloudformation.amazonaws.com
          Policies:
          - PolicyName: S3-access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
              - Effect: "Allow"
                Action:
                - 's3:*'
                Resource: "*"


