AWSTemplateFormatVersion: 2010-09-09

Description: Deploy infrastructure through codepipeline 

Resources: 
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub matthew.holmes-${AWS::StackName} 
#codepipeline
    MyPipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties: 
          ArtifactStore: 
              Location: !Ref MyS3Bucket
              Type: S3
          RestartExecutionOnUpdate: true
          RoleArn: !GetAtt MyCodePipelineExecutionServiceRole.Arn
          Stages: 
          - Actions: 
            - ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: nerdpractitioner
                Repo: stelligent-university
                PollForSourceChanges: 'true'
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:matthewholmes/github/personal-access-token:SecretString:OAuthToken}}'
              InputArtifacts: []
              OutputArtifacts:
              - Name: MyArtifact
              Name: checkout-code
              Region: us-east-1
            Name: Checkout
          - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: mlh-create-changeset-lab12
                PrimarySource: MyArtifact
              InputArtifacts: 
              - Name: MyArtifact
              OutputArtifacts:
              - Name: MyBuildArtifact
              Name: create-change-set
              Region: us-east-1
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                  ProjectName: mlh-execute-changeset-lab12
                  PrimarySource: MyArtifact
              InputArtifacts: 
              - Name: MyArtifact
              OutputArtifacts:
              - Name: MyExecBuildArtifact
              Name: execute-change-set
              Region: us-east-1
            Name: Deploy
          Tags: 
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'

    MyCodeBuildCreateChangeSetProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: mlh-create-changeset-lab12
        Description: create a change set
        ServiceRole: !GetAtt MyCodeBuildExecutionServiceRole.Arn
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Source: 
          BuildSpec: buildspec_create_changeset.yml
          Type: CODEPIPELINE
        TimeoutInMinutes: 10
        Tags:
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'
   
    MyCodeBuildExecuteChangeSetProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: mlh-execute-changeset-lab12
        Description: execute a change set
        ServiceRole: !GetAtt MyCodeBuildExecutionServiceRole.Arn
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Source: 
          BuildSpec: buildspec_execute_changeset.yml
          Type: CODEPIPELINE
        TimeoutInMinutes: 10
        Tags:
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'

#codepipeline execution role to execute cloudformation and access S3
    MyCodePipelineExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codepipeline.amazonaws.com
          Policies:
          - PolicyName: cfn-execution-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                  - 's3:*'
                  - 'cloudformation:*'
                  - 'codebuild:*'
                  - 'iam:PassRole'
                  Resource: "*"

   # execution role that trust codebuild to execute cfn using cli    
    MyCodeBuildExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
          Policies:
          - PolicyName: S3-access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
              - Effect: "Allow"
                Action:
                - 'cloudformation:*'
                - 'logs:*'
                - 'iam:*'
                - 's3:*'
                - 'dynamodb:*'
                Resource: "*"
