AWSTemplateFormatVersion: 2010-09-09

Description: Deploy infrastructure through codepipeline 

Resources: 
#codepipeline
    MyPipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties: 
          ArtifactStore: 
              Location: holmesdemo
              Type: S3
          RestartExecutionOnUpdate: true
          RoleArn: !GetAtt MyCodePipelineExecutionServiceRole.Arn
          Stages: 
          - Actions: 
            - ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: nerdpractitioner
                Repo: stelligent-university
                PollForSourceChanges: 'true'
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:matthewholmes/github/personal-access-token:SecretString:OAuthToken}}'
              InputArtifacts: []
              OutputArtifacts:
              - Name: MyArtifact
              Name: checkout-code
              Region: us-east-1
            Name: checkout
          - Actions:
            - ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: matthew-holmes-lab12
                PrimarySource: MyArtifact
              InputArtifacts: 
              - Name: MyArtifact
              OutputArtifacts:
              - Name: MyBuildArtifact
              Name: build-validate
              Region: us-east-1
            Name: Build
          - Actions: 
            - ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                StackName: bucket-stack-mlh
                TemplatePath: MyArtifact::bucket.yaml
                RoleArn: !GetAtt MyCloudformationExecutionServiceRole.Arn
              OutputArtifacts: []
              InputArtifacts:
              - Name: MyArtifact 
              Name: Create-S3-Bucket
              Region: us-east-1
            Name: Deploy
          - Actions:
            - ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: matthew-holmes-lab12-test
                PrimarySource: MyArtifact
              InputArtifacts: 
              - Name: MyArtifact
              OutputArtifacts:
              - Name: MyTestArtifact
              Name: healthy
              Region: us-east-1
            Name: Test 
          Tags: 
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'

#codebuild project
    MyCodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: matthew-holmes-lab12
        Description: A description about my project
        ServiceRole: !GetAtt MyCodeBuildExecutionServiceRole.Arn
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Source: 
          BuildSpec: buildspec_build.yml
          Type: CODEPIPELINE
        TimeoutInMinutes: 10
        Tags:
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'
   
    MyCodeBuildTesTProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: matthew-holmes-lab12-test
        Description: A description about my project
        ServiceRole: !GetAtt MyCodeBuildExecutionServiceRole.Arn
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Source: 
          BuildSpec: buildspec_test.yml
          Type: CODEPIPELINE
        TimeoutInMinutes: 10
        Tags:
          - Key: user
            Value: matthew.holmes.labs
          - Key: stelligent-u-lesson
            Value: '12.1.2'
          - Key: stelligent-u-lab
            Value: '12.1.2'

#codepipeline execution role to execute cloudformation and access S3
    MyCodePipelineExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codepipeline.amazonaws.com
          Policies:
          - PolicyName: cfn-execution-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                  - 's3:*'
                  - 'codebuild:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                  Resource: "*"

# execution role that trust cloudformation to create an S3 bucket   
    MyCloudformationExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: cloudformation.amazonaws.com
          Policies:
          - PolicyName: S3-access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
              - Effect: "Allow"
                Action:
                - 's3:*'
                Resource: "*"

# execution role that trust codebuild to execute cfn using cli    
    MyCodeBuildExecutionServiceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument: 
            Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
          Policies:
          - PolicyName: S3-access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
              - Effect: "Allow"
                Action:
                - 'cloudformation:*'
                - 'logs:*'
                - 'iam:PassRole'
                - 's3:*'
                Resource: "*"

Outputs:
  CodeBuildRoleARN:
    Description: codebuild execution role Arn
    Value: !GetAtt MyCodeBuildExecutionServiceRole.Arn
