AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an iam role with a managed iam policy"
Resources: 
  DemoIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: holmesdemorole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  DemoIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Managed policy for bgar IAM lab"
      ManagedPolicyName: holmesdemopolicy
      PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - iam:Get*
            - iam:List*
            Resource:
            - '*'
      Users: 
        - !Ref DemoiamRole