AWSTemplateFormatVersion: 2010-09-09

Description: Parameter store

Resources:
  MySSMParameterEngName:
      Type: AWS::SSM::Parameter
      Properties: 
        DataType: text
        Description: engineer's name
        Name: /matthew.holmes.labs/stelligent-u/lab11/matthewholmes
        Type: String
        Value: matthew
  MySSMParameterEngTeam:
      Type: AWS::SSM::Parameter
      Properties: 
        DataType: text
        Description: enginner's team
        Name: /matthew.holmes.labs/stelligent-u/lab11/matthewholmes/team
        Type: String
        Value: StelligentU
  MySSMParameterEngTimeZone:
      Type: AWS::SSM::Parameter
      Properties: 
        DataType: text
        Description: timezone
        Name: /matthew.holmes.labs/stelligent-u/lab11/matthewholmes/timezone
        Type: String
        Value: Eastern
  MySSMParameterEngState:
      Type: AWS::SSM::Parameter
      Properties: 
        DataType: text
        Description: state
        Name: /matthew.holmes.labs/stelligent-u/lab11/matthewholmes/state
        Type: String
        Value: NC
  MySSMParameterEngStartDate:
      Type: AWS::SSM::Parameter
      Properties: 
        DataType: text
        Description: date engineer started
        Name: /matthew.holmes.labs/stelligent-u/lab11/matthewholmes/start-date
        Type: String
        Value: "07/19/2021"



