AWSTemplateFormatVersion: 2010-09-09
Description: Add a resource restriction to the role's policy that limits full access
to the S3 service for just one of the two buckets and allows only
read-only access to the other.
Resources:
   MyS3Bucket1:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: holmesdemobucket
   MyS3Bucket2:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.holmesdemo
   S3RestrictRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/matthew.holmes.labs
            Action: "sts:AssumeRole"
        Policies:
          - PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: 
                - arn:aws:s3:::holmesdemobucket
                - arn:aws:s3:::holmesdemobucket/*
            PolicyName: s3full
          - PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: 
                - 's3:Get*'
                - 's3:List*'
                Resource: arn:aws:s3:::unrestricted.holmesdemo
            PolicyName: s3read
        RoleName: iam-s3-restrict
Outputs:
  RoleArn:
     Description: Arn of s3fullaccess
     Value: !GetAtt S3RestrictRole.Arn