AWSTemplateFormatVersion: 2010-09-09

Description: Cloudwatch logs lab 8.2
 
Resources: 
    DemoLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: 
        LogGroupName: holmesdemo.8.2.1
        RetentionInDays: 60
    
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: holmes-demo-cwlogs 
  
    DemoBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref DemoBucket
        PolicyDocument:
          Statement:
          - Action: 
            - "s3:*"
            Effect: Allow  
            Resource: 
            - "arn:aws:s3:::holmes-demo-cwlogs/*"
            - "arn:aws:s3:::holmes-demo-cwlogs"
            Principal:
               Service: 
               - cloudtrail.amazonaws.com

    DemoCloudWatchRole:
       Type: AWS::IAM::Role
       Properties: 
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - cloudtrail.amazonaws.com
              Action:
              - 'sts:AssumeRole'
          ManagedPolicyArns: 
            - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
          RoleName: !Join ["",[!Ref AWS::Region, cw-role ]] 
          Tags: 
          - Key: user
            Value: matthew.holmes.labs
    DemoCloudTrail:
        Type: AWS::CloudTrail::Trail
        Properties: 
          CloudWatchLogsLogGroupArn: !GetAtt DemoLogGroup.Arn
          CloudWatchLogsRoleArn: !GetAtt DemoCloudWatchRole.Arn 
          IsLogging: true
          S3BucketName: !Ref DemoBucket
          Tags: 
          - Key: user
            Value: matthew.holmes.labs

