AWSTemplateFormatVersion: 2010-09-09
Description: Replace the customer managed policy with AWS managed policies

Resources: 
   IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: iam-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
   EC2Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ec2-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "ec2.amazonaws.com"
              - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess