AWSTemplateFormatVersion: 2010-09-09
Description: "Create a CFN template that specifies an IAM Role. Uses inline policy"
Resources: 
  DemoiamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: holmesdemorole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: holmesdemopolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iam:Get*
              - iam:List*
              Resource:
              - '*'
              
              
              
