AWSTemplateFormatVersion: 2010-09-09
Description: Create a CFN template that creates an IAM Role and makes it possible for
your User to assume that role.
Parameters:
  IAMreadOnly:
    Description: IAM read-only access policy
    Type: String
    Default: arn:aws:iam::aws:policy/IAMReadOnlyAccess
Resources:
   IAMrole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/matthew.holmes.labs
            Action: "sts:AssumeRole"
        ManagedPolicyArns:
        - !Ref IAMreadOnly
        RoleName: iam-read-only