AWSTemplateFormatVersion: 2010-09-09

Description: create a kms cmk

Resources: 
   
   MyCustomerManagedKey:
      Type: AWS::KMS::Key
      Properties: 
        Description: customer managed key
        Enabled: true
        EnableKeyRotation: true
        KeyPolicy:
          Version: '2012-10-17'
          Id: key-default-1
          Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/matthew.holmes.labs
            Action: "kms:*"
            Resource: "*"
        KeyUsage: ENCRYPT_DECRYPT
        PendingWindowInDays: 7
        Tags: 
        - Key: user
          Value: matthew.holmes.labs
        - Key: stelligent-u-lesson
          Value: "10.1"
        - Key: stelligent-u-lab
          Value: "10.1.1"