AWSTemplateFormatVersion: 2010-09-09

Description: Lamdba hello AWS function

Resources: 
    LambdaDemoRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
           Version: 2012-10-17
           Statement:
           - Effect: Allow
             Principal:
                Service: lambda.amazonaws.com
             Action: sts:AssumeRole
        Description: Lambda execution role
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        RoleName: !Join ["",[!Ref AWS::Region, Demolambda-role ]] 
        Tags: 
          - Key: user
            Value: matthew.holmes.labs
    
    HelloAWSFunction:
        Type: AWS::Lambda::Function
        Properties: 
          Code: 
            ZipFile: |
              import json
              
              def lambda_handler(event, context):
                return {
                  'statusCode': 200,
                  'body': json.dumps(event)
                }
                #modified to dump json payload as "event"
          Handler: index.lambda_handler
          FunctionName: HelloAWSLambda
          Description: Hello AWS function
          Role: !GetAtt LambdaDemoRole.Arn 
          Runtime: python3.8
          Tags: 
          - Key: user
            Value: matthew.holmes.labs
          TracingConfig:
              Mode: Active
    
    DemoLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties: 
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt HelloAWSFunction.Arn
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DemoRestApi}/*/*'

    DemoRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Description: A test API
        Name: DemoRestAPI
        EndpointConfiguration:
          Types: 
          - REGIONAL
        Tags: 
        - Key: user
          Value: matthew.holmes.labs
    
    DemoGetMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        RestApiId: !Ref DemoRestApi
        ResourceId: !GetAtt DemoRestApi.RootResourceId
        HttpMethod: GET                 
        AuthorizationType: NONE
        Integration:
          Type: AWS_PROXY          
          IntegrationHttpMethod: POST
          Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloAWSFunction.Arn}/invocations
          
    DemoApiGatewayDeployment:
        DependsOn: DemoGetMethod 
        Type: AWS::ApiGateway::Deployment
        Properties:
          RestApiId: !Ref DemoRestApi
          Description: Demo deployment
          StageName: staging

Outputs:
  RestApiID:
    Description: REST API id
    Value: !Ref DemoRestApi
  RootResourceID:
    Description: Root resource id
    Value: !GetAtt DemoRestApi.RootResourceId
